# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 542e8ffce3507538813f1c2227134562de2e07bfb99e2a6d6baf37e8e4c3bdb510e99222ce510efb3c934f0c8d19d8fccf08e6c97dd5763ba5c07f6b3c2d7b35

test:
  secret_key_base: b1d97cfc7c0041048778d1e06a862b3df51c3a6ce840539b6043bc4a06cf444ba0cf6a07ddbf4bec611787788f9321b2c6dc993889a505bb3fe996ff86dd7fb2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
